import { defineConfig } from "eslint/config";
import globals from "globals";
import babelParser from "@babel/eslint-parser";

export default defineConfig([{
    languageOptions: {
        globals: {
            ...globals.browser,
            ...globals.node,
            angular: true,
            moment: true,
            describe: true,
            beforeEach: true,
            ExpectedConditions: true,
            expect: true,
            it: true,
            inject: true,
            spyOn: true,
            $provide: true,
            $: true,
            jasmine: true,
            afterEach: true,
            beforeAll: true,
            XDate: true,
            dump: true,
            jQuery: true,
            Chart: true,
            Gantt: true,
            by: true,
            element: true,
            browser: true,
            Bloodhound: true,
            Dropzone: true,
            JSONH: true,
            protractor: true,
            identity: true,
            isDate: true,
            __require: true,
            __app: true,
            __database_uri: true,
            __enviroment: true,
            __gcp_idukay_id: true,
            __gcp_idulogs_id: true,
            __offset_time: true,
            __testing: true,
            io: true,
            Promise: true,
            Set: true,
            Uint8Array: true,
            Sentry: true,
            CryptoJS: true,
            Map: true,
            jsQR: true,
        },

        parser: babelParser,
        parserOptions: {
            requireConfigFile: false,
            babelOptions: {
                presets: ["@babel/preset-env"]
            }
        },
    },

    rules: {
        "comma-dangle": 2,
        "no-cond-assign": 2,
        "no-console": 1,
        "arrow-spacing": 2,
        "no-const-assign": 2,
        "no-constant-condition": 2,
        "no-control-regex": 2,
        "no-debugger": 2,
        "no-dupe-args": 2,
        "no-dupe-keys": 2,
        "no-duplicate-case": 2,
        "no-empty": 2,
        "no-empty-character-class": 2,
        "no-ex-assign": 2,
        "no-extra-boolean-cast": 2,
        "no-extra-semi": 2,
        "no-func-assign": 2,
        "no-inner-declarations": 2,
        "no-invalid-regexp": 2,
        "no-irregular-whitespace": 2,
        "no-obj-calls": 2,
        "no-regex-spaces": 2,
        "no-sparse-arrays": 2,
        "no-unreachable": 2,
        "use-isnan": 2,
        "valid-typeof": 2,
        "block-scoped-var": 0,
        complexity: 0,
        "consistent-return": 0,
        curly: 2,
        "default-case": 2,
        "dot-notation": 2,
        eqeqeq: 2,
        "guard-for-in": 2,
        "no-alert": 2,
        "no-caller": 2,
        "no-div-regex": 2,
        "no-else-return": 2,
        "no-eq-null": 2,
        "no-eval": 2,
        "no-extend-native": 2,
        "no-extra-bind": 2,
        "no-fallthrough": 2,
        "no-floating-decimal": 2,
        "no-implied-eval": 2,
        "no-iterator": 2,
        "no-labels": 2,
        "no-lone-blocks": 2,
        "no-loop-func": 2,
        "no-multi-spaces": 2,
        "no-multi-str": 2,
        "no-global-assign": 2,
        "no-new": 2,
        "no-new-func": 2,
        "no-new-wrappers": 2,
        "no-octal": 2,
        "no-octal-escape": 2,
        "no-process-env": 0,
        "no-proto": 2,
        "no-redeclare": 2,
        "no-script-url": 2,
        "no-self-compare": 2,
        "no-sequences": 2,
        "no-unused-expressions": 2,
        "no-void": 2,

        "no-warning-comments": [0, {
            terms: ["todo", "fixme"],
            location: "start",
        }],

        "no-with": 2,
        "wrap-iife": 2,
        yoda: 2,
        strict: 0,
        "no-catch-shadow": 2,
        "no-delete-var": 2,
        "no-label-var": 2,
        "no-shadow-restricted-names": 2,
        "no-undef": 2,
        "no-undef-init": 2,
        "no-unused-vars": 2,

        "no-use-before-define": [2, {
            functions: false,
        }],

        indent: [2, 2, {
            MemberExpression: 0,
        }],

        "brace-style": 1,

        "comma-spacing": [1, {
            before: false,
            after: true,
        }],

        "comma-style": [1, "last"],
        "eol-last": 1,
        "func-names": 0,
        "func-style": 0,

        "key-spacing": [1, {
            beforeColon: false,
            afterColon: true,
        }],

        "new-cap": 0,
        "new-parens": 1,
        "newline-after-var": 0,
        "no-array-constructor": 1,
        "no-inline-comments": 1,
        "no-lonely-if": 1,
        "no-mixed-spaces-and-tabs": 1,

        "no-multiple-empty-lines": [1, {
            max: 2,
        }],

        "no-nested-ternary": 1,
        "no-new-object": 1,
        "func-call-spacing": [1, "never"],
        "no-ternary": 0,
        "no-trailing-spaces": 0,
        "no-extra-parens": 1,
        "operator-assignment": [2, "always"],
        "padded-blocks": [1, "never"],
        "quote-props": [1, "as-needed"],
        quotes: [1, "single"],
        semi: [2, "always"],

        "semi-spacing": [1, {
            before: false,
            after: true,
        }],

        "sort-vars": 0,
        "keyword-spacing": [2],
        "space-before-blocks": [1, "always"],

        "space-before-function-paren": [1, {
            anonymous: "always",
            named: "never",
        }],

        "object-curly-spacing": [1, "never"],
        "space-in-parens": [1, "never"],

        "space-infix-ops": [1, {
            int32Hint: false,
        }],

        "space-unary-ops": [1, {
            words: true,
            nonwords: false,
        }],

        "spaced-comment": [0, "always"],
        "wrap-regex": 0,
        "generator-star-spacing": [2, "before"],
        "max-depth": [2, 3],
        "max-statements": 0,
        "no-bitwise": 0,
    },
}]);